export const rawData = [
    {title:"iPhone 13 Pro Max, 256GB, Sierra Blue - Unlocked", 
      img:"https://images-na.ssl-images-amazon.com/images/I/61i8Vjb17SL._AC_UL160_SR160,160_.jpg", 
      price:'869', 
      rating:'459',
      id:1,
      amount:1},
      {title:"Balancefrom Rubber Encased Hex Dumbbell in Pairs", 
      img:"https://images-na.ssl-images-amazon.com/images/G/01/AmazonExports/Fuji/2021/September/DashboardCards/Fuji_Dash_Fitness_1X._SY304_CB639748186_.jpg", 
      price:'356', 
      rating:'25',
      id:2,
      amount:1},
      {title:"Apple iPhone 12 Pro Max, 256GB, Pacific Blue - Unlocked", 
      img:"https://m.media-amazon.com/images/I/71FuI8YvCNL.__AC_SX300_SY300_QL70_FMwebp_.jpg", 
      price:'640', 
      rating:'25',
      id:3,
      amount:1},
      {title:"Toy Scale Model Airplane 1:400 Fit for B737-400 PH-BDY", 
      img:"https://images-na.ssl-images-amazon.com/images/G/01/AmazonExports/Fuji/2021/September/DashboardCards/Fuji_Dash_Toys_1X._SY304_CB639759658_.jpg", 
      price:'245', 
      rating:'25',
      id:4,
      amount:1},
      {title:"Gibson Home Rockabye Rockaway Dinnerware Set, Service for 4 (Melamine), Matte Green", 
      img:"https://m.media-amazon.com/images/I/61a03gfX9dL._AC_UL320_.jpg", 
      price:'356', 
      rating:'25',
      id:5,
      amount:1},
      {title:"Hamilton Beach Deep Fryer with 2 Frying Baskets, 19 Cups / 4.5 Liters Oil Capacity", 
      img:"https://m.media-amazon.com/images/I/81Jryf8JpHL._AC_UL320_.jpg", 
      price:'183', 
      rating:'25',
      id:6,
      amount:1},
      {title:"LG 34WP60C-B 34-Inch 21:9 Curved UltraWide QHD (3440x1440) VA Display with sRGB 99% Color Gamut", 
      img:"https://m.media-amazon.com/images/I/71xUGwGReSL._AC_SL1500_.jpg", 
      price:'560', 
      rating:'25',
      id:7,
      amount:1},
      {title:"Sceptre 24, Curved 75Hz Gaming LED Monitor Full HD 1080P HDMI VGA Speakers VESA Wall Mount Ready Metal Black", 
      img:"https://m.media-amazon.com/images/I/71P0M7tKjYL._AC_SX679_.jpg", 
      price:'240', 
      rating:'25',
      id:8,
      amount:1},
      {title:"LG 34WP60C-B 34-Inch 21:9 Curved UltraWide QHD (3440x1440) VA Display with sRGB 99% Color Gamut", 
      img:"https://m.media-amazon.com/images/I/71xUGwGReSL._AC_SL1500_.jpg", 
      price:'356', 
      rating:'25',
      id:9,
      amount:1}
]